---
name: "Study of github actions workflow"


on:
  push:
    branches:
      - master
      - testing
      - development
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: "Running Date command"
        run: date
        shell: bash

      - name: "Getting OS details"
        run: cat /etc/os-release
        shell: bash

      - name: "User details"
        run: whoami
        shell: bash

      - name: "Current working directory details before checkout"
        run: |
          pwd
          ls -l

      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name : "Current working directory details after checkout"
        run: |
          pwd
          ls -l

      - name: "Installing Terraform"
        uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.6.6"

      - name: "Terraform version"
        run: terraform version

      - name: "Running script.sh"
        run: |
          chmod +x script.sh
          ./script.sh
